# -*- coding: utf-8 -*-
"""Email _Slicer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10DaPnMQwnFC7zPD-FhOtxkqka7zD8nOx

#Email Slicer

To make an email slicer in Python, we'll need to construct a program that can obtain the email's username and domain name.

As a result, we must split the email into two strings using the '@' separator. Let's look at how to use Python to separate the email and domain name:
"""

#code

#input the mail
email=input("Enter the mail:")
username=email[:email.index('@')]
domain=email[email.index('@')+1:]

# printing result
print("Your user name is :",username," and your domain: ",domain)